#############################################################################
# Makefile for building: jeu
# Generated by qmake (3.0) (Qt 5.1.1) on: Mon Dec 9 17:45:22 2013
# Project:  jeu.pro
# Template: app
# Command: /home/ncapiaumont/Qt5.1.1/5.1.1/gcc/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile jeu.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../../Qt5.1.1/5.1.1/gcc/mkspecs/linux-g++ -I. -I../../../Qt5.1.1/5.1.1/gcc/include -I../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets -I../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork -I../../../Qt5.1.1/5.1.1/gcc/include/QtGui -I../../../Qt5.1.1/5.1.1/gcc/include/QtCore -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/ncapiaumont/Qt5.1.1/5.1.1/gcc -Wl,-rpath,/home/ncapiaumont/Qt5.1.1/5.1.1/gcc/lib
LIBS          = $(SUBLIBS) -L/home/ncapiaumont/Qt5.1.1/5.1.1/gcc/lib -lQt5Widgets -lQt5Network -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/ncapiaumont/Qt5.1.1/5.1.1/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		joueur.cpp \
		emplacement.cpp \
		help.cpp qrc_mesRessources.cpp \
		moc_mainwindow.cpp \
		moc_joueur.cpp \
		moc_emplacement.cpp \
		moc_help.cpp
OBJECTS       = main.o \
		mainwindow.o \
		joueur.o \
		emplacement.o \
		help.o \
		qrc_mesRessources.o \
		moc_mainwindow.o \
		moc_joueur.o \
		moc_emplacement.o \
		moc_help.o
DIST          = ../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/spec_pre.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/common/shell-unix.conf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/common/unix.conf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/common/linux.conf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/common/gcc-base.conf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/common/gcc-base-unix.conf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/common/g++-base.conf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/common/g++-unix.conf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/qconfig.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_clucene.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_designercomponents.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_platformsupport.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_quickparticles.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_v8.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/qt_functions.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/qt_config.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/linux-g++/qmake.conf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/spec_post.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/default_pre.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/unix/default_pre.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/resolve_config.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/default_post.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/qml_debug.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/declarative_debug.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/warn_on.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/qt.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/resources.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/moc.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/unix/opengl.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/uic.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/unix/thread.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/wayland-scanner.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/testcase_targets.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/exceptions.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/yacc.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/lex.prf \
		jeu.pro \
		mesRessources.qrc \
		jeu.pro
QMAKE_TARGET  = jeu
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = jeu


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_help.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: jeu.pro ../../../Qt5.1.1/5.1.1/gcc/mkspecs/linux-g++/qmake.conf ../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/spec_pre.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/common/shell-unix.conf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/common/unix.conf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/common/linux.conf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/common/gcc-base.conf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/common/gcc-base-unix.conf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/common/g++-base.conf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/common/g++-unix.conf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/qconfig.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_clucene.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_designercomponents.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_platformsupport.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_quickparticles.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_v8.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/qt_functions.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/qt_config.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/linux-g++/qmake.conf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/spec_post.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/default_pre.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/unix/default_pre.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/resolve_config.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/default_post.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/qml_debug.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/declarative_debug.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/warn_on.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/qt.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/resources.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/moc.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/unix/opengl.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/uic.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/unix/thread.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/wayland-scanner.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/testcase_targets.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/exceptions.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/yacc.prf \
		../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/lex.prf \
		jeu.pro \
		mesRessources.qrc \
		/home/ncapiaumont/Qt5.1.1/5.1.1/gcc/lib/libQt5Widgets.prl \
		/home/ncapiaumont/Qt5.1.1/5.1.1/gcc/lib/libQt5Network.prl \
		/home/ncapiaumont/Qt5.1.1/5.1.1/gcc/lib/libQt5Gui.prl \
		/home/ncapiaumont/Qt5.1.1/5.1.1/gcc/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile jeu.pro
../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/spec_pre.prf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/common/shell-unix.conf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/common/unix.conf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/common/linux.conf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/common/gcc-base.conf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/common/gcc-base-unix.conf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/common/g++-base.conf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/common/g++-unix.conf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/qconfig.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_clucene.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_core.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_designer.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_designercomponents.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_gui.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_help.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_network.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_platformsupport.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_qml.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_qmldevtools.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_quick.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_quickparticles.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_script.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_sql.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_svg.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_v8.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_x11extras.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_xml.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/qt_functions.prf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/qt_config.prf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/linux-g++/qmake.conf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/spec_post.prf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/exclusive_builds.prf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/default_pre.prf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/unix/default_pre.prf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/resolve_config.prf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/default_post.prf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/qml_debug.prf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/declarative_debug.prf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/warn_on.prf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/qt.prf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/resources.prf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/moc.prf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/unix/opengl.prf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/uic.prf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/unix/thread.prf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/wayland-scanner.prf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/testcase_targets.prf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/exceptions.prf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/yacc.prf:
../../../Qt5.1.1/5.1.1/gcc/mkspecs/features/lex.prf:
jeu.pro:
mesRessources.qrc:
/home/ncapiaumont/Qt5.1.1/5.1.1/gcc/lib/libQt5Widgets.prl:
/home/ncapiaumont/Qt5.1.1/5.1.1/gcc/lib/libQt5Network.prl:
/home/ncapiaumont/Qt5.1.1/5.1.1/gcc/lib/libQt5Gui.prl:
/home/ncapiaumont/Qt5.1.1/5.1.1/gcc/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile jeu.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/jeu1.0.0 || mkdir -p .tmp/jeu1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/jeu1.0.0/ && $(COPY_FILE) --parents mesRessources.qrc .tmp/jeu1.0.0/ && $(COPY_FILE) --parents mainwindow.h joueur.h emplacement.h help.h .tmp/jeu1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp joueur.cpp emplacement.cpp help.cpp .tmp/jeu1.0.0/ && $(COPY_FILE) --parents mainwindow.ui help.ui .tmp/jeu1.0.0/ && (cd `dirname .tmp/jeu1.0.0` && $(TAR) jeu1.0.0.tar jeu1.0.0 && $(COMPRESS) jeu1.0.0.tar) && $(MOVE) `dirname .tmp/jeu1.0.0`/jeu1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/jeu1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_mesRessources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_mesRessources.cpp
qrc_mesRessources.cpp: mesRessources.qrc \
		jeu_fr.qm \
		jeu_jp.qm \
		jeu_kr.qm \
		jeu_de.qm \
		images/jetonRouge.png \
		images/emplVide.png \
		images/jetonBleu.png \
		images/plateau.png
	/home/ncapiaumont/Qt5.1.1/5.1.1/gcc/bin/rcc -name mesRessources mesRessources.qrc -o qrc_mesRessources.cpp

compiler_wayland_server_header_make_all:
compiler_wayland_server_header_clean:
compiler_wayland_client_header_make_all:
compiler_wayland_client_header_clean:
compiler_qtwayland_client_header_make_all:
compiler_qtwayland_client_header_clean:
compiler_qtwayland_server_header_make_all:
compiler_qtwayland_server_header_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_joueur.cpp moc_emplacement.cpp moc_help.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_joueur.cpp moc_emplacement.cpp moc_help.cpp
moc_mainwindow.cpp: ../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QMainWindow \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qmainwindow.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qwidget.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qwindowdefs.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qglobal.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qconfig.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfeatures.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsystemdetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcompilerdetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qprocessordetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qglobalstatic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qbasicatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qgenericatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_msvc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_integrity.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_power.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_alpha.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv7.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv6.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv5.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_bfin.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_ia64.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_mips.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_s390.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_sparc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_x86.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_gcc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_unix.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmutex.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlogging.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qflags.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtypeinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtypetraits.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsysinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobjectdefs.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qnamespace.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qwindowdefs_win.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobject.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstring.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qchar.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qbytearray.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qrefcount.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qarraydata.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringbuilder.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlist.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qalgorithms.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qiterator.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcoreevent.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qscopedpointer.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmetatype.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvarlengtharray.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcontainerfwd.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qisenum.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobject_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmargins.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qrect.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsize.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qpoint.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpaintdevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpalette.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qcolor.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qrgb.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringlist.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qdatastream.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qiodevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qpair.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qregexp.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringmatcher.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qbrush.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvector.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qmatrix.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpolygon.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qregion.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qline.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qtransform.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpainterpath.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qimage.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpixmap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsharedpointer.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qshareddata.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qhash.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfont.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfontmetrics.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfontinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qsizepolicy.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qcursor.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qkeysequence.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qevent.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvariant.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qdebug.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtextstream.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlocale.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qset.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcontiguouscache.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qurl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qurlquery.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfile.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfiledevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qvector2d.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qtouchdevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qtabwidget.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qicon.h \
		joueur.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QLabel \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qlabel.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qframe.h \
		emplacement.h \
		mainwindow.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/QTcpSocket \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/qtcpsocket.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/qabstractsocket.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/QTcpServer \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/qtcpserver.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/qhostaddress.h \
		mainwindow.h
	/home/ncapiaumont/Qt5.1.1/5.1.1/gcc/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_joueur.cpp: ../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QLabel \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qlabel.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qframe.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qwidget.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qwindowdefs.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qglobal.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qconfig.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfeatures.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsystemdetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcompilerdetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qprocessordetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qglobalstatic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qbasicatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qgenericatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_msvc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_integrity.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_power.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_alpha.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv7.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv6.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv5.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_bfin.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_ia64.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_mips.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_s390.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_sparc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_x86.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_gcc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_unix.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmutex.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlogging.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qflags.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtypeinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtypetraits.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsysinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobjectdefs.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qnamespace.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qwindowdefs_win.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobject.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstring.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qchar.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qbytearray.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qrefcount.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qarraydata.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringbuilder.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlist.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qalgorithms.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qiterator.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcoreevent.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qscopedpointer.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmetatype.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvarlengtharray.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcontainerfwd.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qisenum.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobject_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmargins.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qrect.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsize.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qpoint.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpaintdevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpalette.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qcolor.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qrgb.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringlist.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qdatastream.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qiodevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qpair.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qregexp.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringmatcher.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qbrush.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvector.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qmatrix.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpolygon.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qregion.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qline.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qtransform.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpainterpath.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qimage.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpixmap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsharedpointer.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qshareddata.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qhash.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfont.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfontmetrics.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfontinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qsizepolicy.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qcursor.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qkeysequence.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qevent.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvariant.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qdebug.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtextstream.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlocale.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qset.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcontiguouscache.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qurl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qurlquery.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfile.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfiledevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qvector2d.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qtouchdevice.h \
		joueur.h
	/home/ncapiaumont/Qt5.1.1/5.1.1/gcc/bin/moc $(DEFINES) $(INCPATH) joueur.h -o moc_joueur.cpp

moc_emplacement.cpp: ../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QLabel \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qlabel.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qframe.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qwidget.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qwindowdefs.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qglobal.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qconfig.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfeatures.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsystemdetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcompilerdetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qprocessordetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qglobalstatic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qbasicatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qgenericatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_msvc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_integrity.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_power.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_alpha.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv7.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv6.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv5.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_bfin.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_ia64.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_mips.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_s390.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_sparc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_x86.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_gcc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_unix.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmutex.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlogging.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qflags.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtypeinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtypetraits.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsysinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobjectdefs.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qnamespace.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qwindowdefs_win.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobject.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstring.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qchar.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qbytearray.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qrefcount.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qarraydata.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringbuilder.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlist.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qalgorithms.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qiterator.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcoreevent.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qscopedpointer.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmetatype.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvarlengtharray.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcontainerfwd.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qisenum.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobject_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmargins.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qrect.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsize.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qpoint.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpaintdevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpalette.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qcolor.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qrgb.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringlist.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qdatastream.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qiodevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qpair.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qregexp.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringmatcher.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qbrush.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvector.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qmatrix.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpolygon.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qregion.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qline.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qtransform.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpainterpath.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qimage.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpixmap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsharedpointer.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qshareddata.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qhash.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfont.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfontmetrics.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfontinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qsizepolicy.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qcursor.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qkeysequence.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qevent.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvariant.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qdebug.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtextstream.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlocale.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qset.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcontiguouscache.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qurl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qurlquery.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfile.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfiledevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qvector2d.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qtouchdevice.h \
		mainwindow.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QMainWindow \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qmainwindow.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qtabwidget.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qicon.h \
		joueur.h \
		emplacement.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/QTcpSocket \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/qtcpsocket.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/qabstractsocket.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/QTcpServer \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/qtcpserver.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/qhostaddress.h \
		emplacement.h
	/home/ncapiaumont/Qt5.1.1/5.1.1/gcc/bin/moc $(DEFINES) $(INCPATH) emplacement.h -o moc_emplacement.cpp

moc_help.cpp: ../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QDialog \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qdialog.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qwidget.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qwindowdefs.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qglobal.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qconfig.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfeatures.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsystemdetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcompilerdetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qprocessordetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qglobalstatic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qbasicatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qgenericatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_msvc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_integrity.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_power.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_alpha.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv7.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv6.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv5.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_bfin.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_ia64.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_mips.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_s390.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_sparc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_x86.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_gcc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_unix.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmutex.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlogging.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qflags.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtypeinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtypetraits.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsysinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobjectdefs.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qnamespace.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qwindowdefs_win.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobject.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstring.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qchar.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qbytearray.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qrefcount.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qarraydata.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringbuilder.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlist.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qalgorithms.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qiterator.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcoreevent.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qscopedpointer.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmetatype.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvarlengtharray.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcontainerfwd.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qisenum.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobject_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmargins.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qrect.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsize.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qpoint.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpaintdevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpalette.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qcolor.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qrgb.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringlist.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qdatastream.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qiodevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qpair.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qregexp.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringmatcher.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qbrush.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvector.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qmatrix.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpolygon.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qregion.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qline.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qtransform.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpainterpath.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qimage.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpixmap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsharedpointer.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qshareddata.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qhash.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfont.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfontmetrics.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfontinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qsizepolicy.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qcursor.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qkeysequence.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qevent.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvariant.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qdebug.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtextstream.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlocale.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qset.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcontiguouscache.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qurl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qurlquery.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfile.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfiledevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qvector2d.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qtouchdevice.h \
		ui_help.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/QVariant \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QAction \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qaction.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qicon.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qactiongroup.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QApplication \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qapplication.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcoreapplication.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qeventloop.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qdesktopwidget.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qguiapplication.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qinputmethod.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QButtonGroup \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qbuttongroup.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QHBoxLayout \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qboxlayout.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qlayout.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qlayoutitem.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qgridlayout.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QHeaderView \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qheaderview.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qabstractitemview.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qabstractscrollarea.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qframe.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qabstractitemmodel.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qitemselectionmodel.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qabstractitemdelegate.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qstyleoption.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qabstractspinbox.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qvalidator.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qregularexpression.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qslider.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qabstractslider.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qstyle.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qtabbar.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qtabwidget.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qrubberband.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QLabel \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qlabel.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QPushButton \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qpushbutton.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qabstractbutton.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QSpacerItem \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QVBoxLayout \
		help.h
	/home/ncapiaumont/Qt5.1.1/5.1.1/gcc/bin/moc $(DEFINES) $(INCPATH) help.h -o moc_help.cpp

compiler_wayland_code_make_all:
compiler_wayland_code_clean:
compiler_qtwayland_client_code_make_all:
compiler_qtwayland_client_code_clean:
compiler_qtwayland_server_code_make_all:
compiler_qtwayland_server_code_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_help.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_help.h
ui_mainwindow.h: mainwindow.ui
	/home/ncapiaumont/Qt5.1.1/5.1.1/gcc/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_help.h: help.ui
	/home/ncapiaumont/Qt5.1.1/5.1.1/gcc/bin/uic help.ui -o ui_help.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QMainWindow \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qmainwindow.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qwidget.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qwindowdefs.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qglobal.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qconfig.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfeatures.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsystemdetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcompilerdetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qprocessordetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qglobalstatic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qbasicatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qgenericatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_msvc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_integrity.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_power.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_alpha.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv7.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv6.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv5.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_bfin.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_ia64.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_mips.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_s390.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_sparc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_x86.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_gcc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_unix.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmutex.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlogging.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qflags.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtypeinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtypetraits.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsysinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobjectdefs.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qnamespace.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qwindowdefs_win.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobject.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstring.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qchar.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qbytearray.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qrefcount.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qarraydata.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringbuilder.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlist.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qalgorithms.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qiterator.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcoreevent.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qscopedpointer.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmetatype.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvarlengtharray.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcontainerfwd.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qisenum.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobject_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmargins.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qrect.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsize.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qpoint.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpaintdevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpalette.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qcolor.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qrgb.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringlist.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qdatastream.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qiodevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qpair.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qregexp.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringmatcher.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qbrush.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvector.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qmatrix.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpolygon.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qregion.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qline.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qtransform.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpainterpath.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qimage.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpixmap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsharedpointer.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qshareddata.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qhash.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfont.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfontmetrics.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfontinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qsizepolicy.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qcursor.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qkeysequence.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qevent.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvariant.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qdebug.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtextstream.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlocale.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qset.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcontiguouscache.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qurl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qurlquery.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfile.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfiledevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qvector2d.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qtouchdevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qtabwidget.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qicon.h \
		joueur.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QLabel \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qlabel.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qframe.h \
		emplacement.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/QTcpSocket \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/qtcpsocket.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/qabstractsocket.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/QTcpServer \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/qtcpserver.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/qhostaddress.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QApplication \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qapplication.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcoreapplication.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qeventloop.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qdesktopwidget.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qguiapplication.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qinputmethod.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/QTranslator \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtranslator.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/QFile \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QMainWindow \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qmainwindow.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qwidget.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qwindowdefs.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qglobal.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qconfig.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfeatures.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsystemdetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcompilerdetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qprocessordetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qglobalstatic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qbasicatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qgenericatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_msvc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_integrity.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_power.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_alpha.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv7.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv6.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv5.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_bfin.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_ia64.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_mips.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_s390.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_sparc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_x86.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_gcc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_unix.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmutex.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlogging.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qflags.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtypeinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtypetraits.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsysinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobjectdefs.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qnamespace.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qwindowdefs_win.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobject.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstring.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qchar.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qbytearray.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qrefcount.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qarraydata.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringbuilder.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlist.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qalgorithms.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qiterator.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcoreevent.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qscopedpointer.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmetatype.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvarlengtharray.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcontainerfwd.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qisenum.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobject_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmargins.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qrect.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsize.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qpoint.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpaintdevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpalette.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qcolor.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qrgb.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringlist.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qdatastream.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qiodevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qpair.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qregexp.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringmatcher.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qbrush.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvector.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qmatrix.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpolygon.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qregion.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qline.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qtransform.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpainterpath.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qimage.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpixmap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsharedpointer.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qshareddata.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qhash.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfont.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfontmetrics.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfontinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qsizepolicy.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qcursor.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qkeysequence.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qevent.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvariant.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qdebug.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtextstream.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlocale.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qset.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcontiguouscache.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qurl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qurlquery.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfile.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfiledevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qvector2d.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qtouchdevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qtabwidget.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qicon.h \
		joueur.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QLabel \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qlabel.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qframe.h \
		emplacement.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/QTcpSocket \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/qtcpsocket.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/qabstractsocket.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/QTcpServer \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/qtcpserver.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/qhostaddress.h \
		ui_mainwindow.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/QVariant \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QAction \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qaction.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qactiongroup.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QApplication \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qapplication.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcoreapplication.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qeventloop.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qdesktopwidget.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qguiapplication.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qinputmethod.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QButtonGroup \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qbuttongroup.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QCheckBox \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qcheckbox.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qabstractbutton.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QGridLayout \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qgridlayout.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qlayout.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qlayoutitem.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qboxlayout.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QHBoxLayout \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QHeaderView \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qheaderview.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qabstractitemview.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qabstractscrollarea.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qabstractitemmodel.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qitemselectionmodel.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qabstractitemdelegate.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qstyleoption.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qabstractspinbox.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qvalidator.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qregularexpression.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qslider.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qabstractslider.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qstyle.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qtabbar.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qrubberband.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QLineEdit \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qlineedit.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qtextcursor.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qtextformat.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpen.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qtextoption.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QListWidget \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qlistwidget.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qlistview.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QMenu \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qmenu.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QMenuBar \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qmenubar.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QProgressBar \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qprogressbar.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QPushButton \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qpushbutton.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QStackedWidget \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qstackedwidget.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QStatusBar \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qstatusbar.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QVBoxLayout \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QWidget \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/QTimer \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtimer.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qbasictimer.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QInputDialog \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qinputdialog.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qdialog.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/QDebug \
		help.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QDialog \
		ui_help.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QSpacerItem
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

joueur.o: joueur.cpp joueur.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QLabel \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qlabel.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qframe.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qwidget.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qwindowdefs.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qglobal.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qconfig.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfeatures.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsystemdetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcompilerdetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qprocessordetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qglobalstatic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qbasicatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qgenericatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_msvc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_integrity.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_power.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_alpha.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv7.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv6.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv5.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_bfin.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_ia64.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_mips.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_s390.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_sparc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_x86.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_gcc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_unix.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmutex.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlogging.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qflags.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtypeinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtypetraits.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsysinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobjectdefs.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qnamespace.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qwindowdefs_win.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobject.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstring.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qchar.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qbytearray.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qrefcount.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qarraydata.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringbuilder.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlist.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qalgorithms.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qiterator.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcoreevent.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qscopedpointer.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmetatype.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvarlengtharray.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcontainerfwd.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qisenum.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobject_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmargins.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qrect.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsize.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qpoint.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpaintdevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpalette.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qcolor.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qrgb.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringlist.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qdatastream.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qiodevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qpair.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qregexp.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringmatcher.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qbrush.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvector.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qmatrix.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpolygon.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qregion.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qline.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qtransform.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpainterpath.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qimage.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpixmap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsharedpointer.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qshareddata.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qhash.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfont.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfontmetrics.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfontinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qsizepolicy.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qcursor.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qkeysequence.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qevent.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvariant.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qdebug.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtextstream.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlocale.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qset.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcontiguouscache.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qurl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qurlquery.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfile.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfiledevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qvector2d.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qtouchdevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/QPainter \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpainter.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qtextoption.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o joueur.o joueur.cpp

emplacement.o: emplacement.cpp emplacement.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QLabel \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qlabel.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qframe.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qwidget.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qwindowdefs.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qglobal.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qconfig.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfeatures.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsystemdetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcompilerdetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qprocessordetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qglobalstatic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qbasicatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qgenericatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_msvc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_integrity.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_power.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_alpha.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv7.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv6.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv5.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_bfin.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_ia64.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_mips.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_s390.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_sparc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_x86.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_gcc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_unix.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmutex.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlogging.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qflags.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtypeinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtypetraits.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsysinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobjectdefs.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qnamespace.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qwindowdefs_win.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobject.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstring.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qchar.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qbytearray.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qrefcount.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qarraydata.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringbuilder.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlist.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qalgorithms.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qiterator.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcoreevent.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qscopedpointer.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmetatype.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvarlengtharray.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcontainerfwd.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qisenum.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobject_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmargins.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qrect.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsize.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qpoint.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpaintdevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpalette.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qcolor.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qrgb.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringlist.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qdatastream.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qiodevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qpair.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qregexp.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringmatcher.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qbrush.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvector.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qmatrix.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpolygon.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qregion.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qline.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qtransform.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpainterpath.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qimage.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpixmap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsharedpointer.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qshareddata.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qhash.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfont.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfontmetrics.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfontinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qsizepolicy.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qcursor.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qkeysequence.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qevent.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvariant.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qdebug.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtextstream.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlocale.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qset.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcontiguouscache.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qurl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qurlquery.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfile.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfiledevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qvector2d.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qtouchdevice.h \
		mainwindow.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QMainWindow \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qmainwindow.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qtabwidget.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qicon.h \
		joueur.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/QTcpSocket \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/qtcpsocket.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/qabstractsocket.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/QTcpServer \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/qtcpserver.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtNetwork/qhostaddress.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/QDebug \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/QPainter \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpainter.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qtextoption.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpen.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QStatusBar \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qstatusbar.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/QMouseEvent
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o emplacement.o emplacement.cpp

help.o: help.cpp help.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QDialog \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qdialog.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qwidget.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qwindowdefs.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qglobal.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qconfig.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfeatures.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsystemdetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcompilerdetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qprocessordetection.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qglobalstatic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qbasicatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qgenericatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_msvc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_integrity.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_power.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_alpha.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv7.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv6.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_armv5.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_bfin.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_ia64.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_mips.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_s390.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_sparc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_x86.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_gcc.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qatomic_unix.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmutex.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlogging.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qflags.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtypeinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtypetraits.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsysinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobjectdefs.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qnamespace.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qwindowdefs_win.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobject.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstring.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qchar.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qbytearray.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qrefcount.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qarraydata.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringbuilder.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlist.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qalgorithms.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qiterator.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcoreevent.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qscopedpointer.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmetatype.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvarlengtharray.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcontainerfwd.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qisenum.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qobject_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmargins.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qrect.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsize.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qpoint.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpaintdevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpalette.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qcolor.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qrgb.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringlist.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qdatastream.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qiodevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qpair.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qregexp.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qstringmatcher.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qbrush.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvector.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qmatrix.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpolygon.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qregion.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qline.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qtransform.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpainterpath.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qimage.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qpixmap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsharedpointer.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qshareddata.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qhash.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfont.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfontmetrics.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qfontinfo.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qsizepolicy.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qcursor.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qkeysequence.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qevent.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qvariant.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qmap.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qdebug.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qtextstream.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qlocale.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qset.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcontiguouscache.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qurl.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qurlquery.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfile.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qfiledevice.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qvector2d.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qtouchdevice.h \
		ui_help.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/QVariant \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QAction \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qaction.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qicon.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qactiongroup.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QApplication \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qapplication.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qcoreapplication.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qeventloop.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qdesktopwidget.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qguiapplication.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qinputmethod.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QButtonGroup \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qbuttongroup.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QHBoxLayout \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qboxlayout.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qlayout.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qlayoutitem.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qgridlayout.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QHeaderView \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qheaderview.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qabstractitemview.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qabstractscrollarea.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qframe.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qabstractitemmodel.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qitemselectionmodel.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qabstractitemdelegate.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qstyleoption.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qabstractspinbox.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtGui/qvalidator.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtCore/qregularexpression.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qslider.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qabstractslider.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qstyle.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qtabbar.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qtabwidget.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qrubberband.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QLabel \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qlabel.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QPushButton \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qpushbutton.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/qabstractbutton.h \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QSpacerItem \
		../../../Qt5.1.1/5.1.1/gcc/include/QtWidgets/QVBoxLayout
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o help.o help.cpp

qrc_mesRessources.o: qrc_mesRessources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_mesRessources.o qrc_mesRessources.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_joueur.o: moc_joueur.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_joueur.o moc_joueur.cpp

moc_emplacement.o: moc_emplacement.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_emplacement.o moc_emplacement.cpp

moc_help.o: moc_help.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_help.o moc_help.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

